// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pio_counter //
// ----------- //

#define pio_counter_wrap_target 2
#define pio_counter_wrap 18

#define pio_counter_offset_start 0u

static const uint16_t pio_counter_program_instructions[] = {
    0xe040, //  0: set    y, 0                       
    0xe021, //  1: set    x, 1                       
            //     .wrap_target
    0xa0c3, //  2: mov    isr, null                  
    0x00c5, //  3: jmp    pin, 5                     
    0x000b, //  4: jmp    11                         
    0x0049, //  5: jmp    x--, 9                     
    0xa04a, //  6: mov    y, !y                      
    0x0088, //  7: jmp    y--, 8                     
    0xa04a, //  8: mov    y, !y                      
    0xe021, //  9: set    x, 1                       
    0xa0c1, // 10: mov    isr, x                     
    0xe020, // 11: set    x, 0                       
    0x8080, // 12: pull   noblock                    
    0xa027, // 13: mov    x, osr                     
    0xa0e6, // 14: mov    osr, isr                   
    0x0032, // 15: jmp    !x, 18                     
    0xa0c2, // 16: mov    isr, y                     
    0x8000, // 17: push   noblock                    
    0xa027, // 18: mov    x, osr                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_counter_program = {
    .instructions = pio_counter_program_instructions,
    .length = 19,
    .origin = -1,
};

static inline pio_sm_config pio_counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_counter_wrap_target, offset + pio_counter_wrap);
    return c;
}

static inline void pio_counter_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    gpio_pull_down(pin);
    pio_sm_config c = pio_counter_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin);
    sm_config_set_jmp_pin(&c, pin);
    sm_config_set_in_shift(&c, false, false, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_NONE);

    sm_config_set_clkdiv(&c, div);

    pio_sm_init(pio, sm, offset, &c);
	pio_sm_set_enabled(pio, sm, true);
}

static inline void pio_counter_request_count(PIO pio, uint sm) {
	pio->txf[sm] = 1;
}
static inline int32_t pio_counter_fetch_count(PIO pio, uint sm) {
	while (pio_sm_is_rx_fifo_empty(pio, sm))
		tight_loop_contents();
	return pio->rxf[sm];
}
static inline int32_t pio_counter_get_count(PIO pio, uint sm) {
	pio_counter_request_count(pio, sm);
	return pio_counter_fetch_count(pio, sm);
}

#endif
